### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by speedywizard**

### CODE REVIEW

**Comment by travis-architect** [comment]
@AndriiMysko @speedywizard  is it deployed somewhere? how to test this in action? if it is not deployed yet, can you please set up the environment so I can test this. Thanks

**Comment by speedywizard** [comment]
@travis-architect , Cesar is taking care of the deployment - please ask him for more details

**Comment by shairyar** [comment]
Env URL https://staging-tci-vcs-proxy.travis-ci.com/

**Comment by travis-architect** [comment]
@AndriiMysko @speedywizard I have tested this and here are my findings,
Login/signup is working.
First adding the server was working, but connecting it to the server does not work.
here is what I have done:

- logged on assembla
- created a p4 repository
- Created a p4config.txt file with the following contents:
```
    P4PORT=ssl:p4-us.assembla.com:30022
    P4USER=williamjames998877
    P4CHARSET=utf8
    P4CLIENT=vcstest001
```
- Ran export P4CONFIG=p4config.txt
- Ran P4TICKETS=/tmp/p4ticket p4 login -a 
- When creating the new server provider, provided ssl:p4-us.assembla.com:30022  for URL
- When clicking on Connect, provided username williamjames998877  and pasted the first line of /tmp/p4ticket file into the token field (it looks similar to ec2-fs5:2357=williamjames998877:B12BA80CD64A952907E6DDBDD8F99B46
But it did not authenticated.
Attached is the screenshot of the error.
Screenshot 2021-09-21 at 5 34 09 PM

what else I am supposed to do to successfully authenticate the server?

After this error the site was not working properly, like the cancel button was not working, neither clicking on the logo was working.

**Comment by GbArc** [comment]
merged vcsproxy-org, closing this one

**Pull request closed without merging**
